{{- if .Values.frontendConfig.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.frontendConfig.name }}
spec:
{{ toYaml .Values.frontendConfig.config | indent 2 }}
{{- end }}