{{- if .Values.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.managedCertificate.name }}
spec:
  domains: 
    {{- toYaml .Values.managedCertificate.domains | nindent 2 }}
{{- end }}