{{- if .Values.serving.enabled }}
{{- if .Values.serving.configuration.enabled }}
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: {{ .Values.serving.configuration.name | default (printf "%s-config" (include "knative.fullname" .)) }}
  namespace: {{ include "knative.namespace" . }}
  {{- with .Values.serving.configuration.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serving.configuration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.serving.configuration.spec.template.metadata.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serving.configuration.spec.template.metadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "knative.serviceAccountName" . }}
      {{- end }}
      containers:
        {{- range .Values.serving.configuration.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .ports }}
          ports:
            {{- toYaml .ports | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}

